// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW-hRDKewXfJTDaaqd7T9yVrj-X9rVBYY',
    appId: '1:1048534413851:web:792e76f3d82ce69c59febe',
    messagingSenderId: '1048534413851',
    projectId: 'recipeapp-4214e',
    authDomain: 'recipeapp-4214e.firebaseapp.com',
    storageBucket: 'recipeapp-4214e.appspot.com',
    measurementId: 'G-9SB7NTK4N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ACUUxOfReTiJE-Lwnx0vMzPhbKF-it4',
    appId: '1:1048534413851:android:9d3e0a016dc498b259febe',
    messagingSenderId: '1048534413851',
    projectId: 'recipeapp-4214e',
    storageBucket: 'recipeapp-4214e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2GrM5udTbtiN3rBcHqw7kiwIo6r3SZcY',
    appId: '1:1048534413851:ios:ef0cba6d85691cda59febe',
    messagingSenderId: '1048534413851',
    projectId: 'recipeapp-4214e',
    storageBucket: 'recipeapp-4214e.appspot.com',
    iosBundleId: 'com.example.foodrecipe',
  );
}
